INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (1, "Adam Sandler", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (2, "Dwayne Johnson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (3, "Vin Diesel", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (4, "Leonardo Dicaprio", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (5, "Chris Evans", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (6, "Robert Downey Jr", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (7, "Chris Hemsworth", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (8, "Tom Holland", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (9, "Scarlett Johansson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (10, "John Travolta", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (11, "Samuel L Jackson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (12, "Woody Harrelson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (13, "Tom Hanks", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (14, "Mark Wahlberg", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (15, "Jennifer Aniston", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (16, "Jennifer Lawrence", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (17, "Chris Pratt", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (18, "Rowan Atkinson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (19, "Kevin James", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (20, "Chris Rock", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (21, "Owen Wilson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (22, "Jackie Chan", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (23, "Emma Watson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (24, "Daniel Radcliffe", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (25, "Paul Walker", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (26, "Snoop Dogg", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (27, "Emma Stone", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (28, "Seth Green", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (29, "Randy Orton", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (30, "Macaulay Culkin", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (31, "Brenda Song", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (32, "Karen Gillan", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (33, "Kevin Hart", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (34, "Tyrese Gibson", "");
INSERT INTO filmtracker.actors (actor_id, name, filename) VALUES (35, "Jack Black", "");


